<?php

return [
    'product_type' => [
        'admin_name' => 'Product Type',
        'translations' => [
            'ar' => 'نوع المنتج',
            'en' => 'Product Type',
        ],
        'type' => 'text',
        'group' => 'Product Details',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'target_gender' => [
        'admin_name' => 'Target Gender',
        'translations' => [
            'ar' => 'الفئة المستهدفة',
            'en' => 'Target Gender',
        ],
        'type' => 'select',
        'group' => 'Product Details',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'target_age' => [
        'admin_name' => 'Target Age',
        'translations' => [
            'ar' => 'العمر المناسب',
            'en' => 'Target Age',
        ],
        'type' => 'text',
        'group' => 'Product Details',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'estimated_material' => [
        'admin_name' => 'Estimated Material',
        'translations' => [
            'ar' => 'الخامة التقديرية',
            'en' => 'Estimated Material',
        ],
        'type' => 'text',
        'group' => 'Product Details',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'estimated_quality_level' => [
        'admin_name' => 'Estimated Quality Level',
        'translations' => [
            'ar' => 'مستوى الجودة التقديري',
            'en' => 'Estimated Quality Level',
        ],
        'type' => 'select',
        'group' => 'Product Details',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'product_style' => [
        'admin_name' => 'Product Style',
        'translations' => [
            'ar' => 'ستايل المنتج',
            'en' => 'Product Style',
        ],
        'type' => 'text',
        'group' => 'Product Details',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'suitable_usage' => [
        'admin_name' => 'Suitable Usage',
        'translations' => [
            'ar' => 'الاستخدام المناسب',
            'en' => 'Suitable Usage',
        ],
        'type' => 'text',
        'group' => 'Product Details',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'shape' => [
        'admin_name' => 'Shape',
        'translations' => [
            'ar' => 'الشكل',
            'en' => 'Shape',
        ],
        'type' => 'textarea',
        'group' => 'Construction',
        'required' => false,
        'filterable' => false,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'compartments' => [
        'admin_name' => 'Compartments',
        'translations' => [
            'ar' => 'الأقسام الداخلية',
            'en' => 'Compartments',
        ],
        'type' => 'textarea',
        'group' => 'Construction',
        'required' => false,
        'filterable' => false,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'pockets' => [
        'admin_name' => 'Pockets',
        'translations' => [
            'ar' => 'الجيوب',
            'en' => 'Pockets',
        ],
        'type' => 'textarea',
        'group' => 'Construction',
        'required' => false,
        'filterable' => false,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'handles' => [
        'admin_name' => 'Handles',
        'translations' => [
            'ar' => 'المقابض',
            'en' => 'Handles',
        ],
        'type' => 'textarea',
        'group' => 'Construction',
        'required' => false,
        'filterable' => false,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'shoulder_straps' => [
        'admin_name' => 'Shoulder Straps',
        'translations' => [
            'ar' => 'أحزمة الكتف',
            'en' => 'Shoulder Straps',
        ],
        'type' => 'textarea',
        'group' => 'Construction',
        'required' => false,
        'filterable' => false,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'closure_type' => [
        'admin_name' => 'Closure Type',
        'translations' => [
            'ar' => 'نوع الغلق',
            'en' => 'Closure Type',
        ],
        'type' => 'select',
        'group' => 'Construction',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'pattern' => [
        'admin_name' => 'Pattern',
        'translations' => [
            'ar' => 'النقشة أو الرسومات',
            'en' => 'Pattern',
        ],
        'type' => 'textarea',
        'group' => 'Design',
        'required' => false,
        'filterable' => false,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'printed_characters' => [
        'admin_name' => 'Printed Characters',
        'translations' => [
            'ar' => 'الشخصيات المطبوعة',
            'en' => 'Printed Characters',
        ],
        'type' => 'textarea',
        'group' => 'Design',
        'required' => false,
        'filterable' => false,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'unique_characteristics' => [
        'admin_name' => 'Unique Characteristics',
        'translations' => [
            'ar' => 'الخصائص المميزة',
            'en' => 'Unique Characteristics',
        ],
        'type' => 'textarea',
        'group' => 'Design',
        'required' => false,
        'filterable' => false,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'selling_points' => [
        'admin_name' => 'Selling Points',
        'translations' => [
            'ar' => 'نقاط البيع',
            'en' => 'Selling Points',
        ],
        'type' => 'textarea',
        'group' => 'Design',
        'required' => false,
        'filterable' => false,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'size' => [
        'admin_name' => 'Size',
        'translations' => [
            'ar' => 'المقاس',
            'en' => 'Size',
        ],
        'type' => 'select',
        'group' => 'Specifications',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
        'options' => [
            '10 inch',
            '11 inch',
            '12 inch',
            '13 inch',
            '14 inch',
            '15 inch',
            '15.6 inch',
            '16 inch',
            '17 inch',
            '18 inch',
            '20 inch',
            '24 inch',
        ],
    ],

    'dimensions' => [
        'admin_name' => 'Dimensions',
        'translations' => [
            'ar' => 'الأبعاد',
            'en' => 'Dimensions',
        ],
        'type' => 'text',
        'group' => 'Specifications',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'capacity' => [
        'admin_name' => 'Capacity',
        'translations' => [
            'ar' => 'السعة',
            'en' => 'Capacity',
        ],
        'type' => 'text',
        'group' => 'Specifications',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'school_stage' => [
        'admin_name' => 'School Stage',
        'translations' => [
            'ar' => 'المرحلة الدراسية',
            'en' => 'School Stage',
        ],
        'type' => 'select',
        'group' => 'Meta Information',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'usage' => [
        'admin_name' => 'Usage',
        'translations' => [
            'ar' => 'الاستخدام',
            'en' => 'Usage',
        ],
        'type' => 'text',
        'group' => 'Meta Information',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'occasion' => [
        'admin_name' => 'Occasion',
        'translations' => [
            'ar' => 'المناسبة',
            'en' => 'Occasion',
        ],
        'type' => 'text',
        'group' => 'Meta Information',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'available_colors' => [
        'admin_name' => 'Available Colors',
        'translations' => [
            'ar' => 'الألوان المتاحة',
            'en' => 'Available Colors',
        ],
        'type' => 'multiselect',
        'group' => 'Catalog',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
        'applies_to' => 'parent',
        'options' => [
            'Red',
            'Green',
            'Yellow',
            'Black',
            'White',
            'Mint Green',
            'Navy',
            'Pink',
            'Turquoise',
            'Purple',
            'Blue',
            'Ice Blue',
            'Lavender',
            'Pink Mint',
            'Mint',
            'Sky Blue',
            'Black Grey',
            'Navy Grey',
            'Black Brown',
            'Navy Green',
            'Navy Pink',
            'Dark Green',
            'Beige Yellow',
            'Pink Yellow',
            'Mauve',
            'Navy Tan',
            'Royal Blue',
            'Navy Red',
            'Grey Black',
            'Olive Green',
            'Grey',
            'Beige',
            'Grey Brown',
        ],
    ],

];
