<?php

return [
    'product_type' => [
        'admin_name' => 'Product Type',
        'translations' => [
            'ar' => 'نوع المنتج',
            'en' => 'Product Type',
        ],
        'type' => 'text',
        'group' => 'Product Details',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'product_type', 'ar' => 'product_type_ar'],
    ],

    'target_gender' => [
        'admin_name' => 'Target Gender',
        'translations' => [
            'ar' => 'الفئة المستهدفة',
            'en' => 'Target Gender',
        ],
        'type' => 'select',
        'group' => 'Product Details',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'target_age' => [
        'admin_name' => 'Target Age',
        'translations' => [
            'ar' => 'العمر المناسب',
            'en' => 'Target Age',
        ],
        'type' => 'text',
        'group' => 'Product Details',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'target_age', 'ar' => 'target_age_ar'],
    ],

    'estimated_material' => [
        'admin_name' => 'Material',
        'translations' => [
            'ar' => 'الخامة',
            'en' => 'Material',
        ],
        'type' => 'text',
        'group' => 'Product Details',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'estimated_material', 'ar' => 'estimated_material_ar'],
    ],

    'estimated_quality_level' => [
        'admin_name' => 'Quality Level',
        'translations' => [
            'ar' => 'مستوى الجودة',
            'en' => 'Quality Level',
        ],
        'type' => 'select',
        'group' => 'Product Details',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'product_style' => [
        'admin_name' => 'Product Style',
        'translations' => [
            'ar' => 'ستايل المنتج',
            'en' => 'Product Style',
        ],
        'type' => 'text',
        'group' => 'Product Details',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'product_style', 'ar' => 'product_style_ar'],
    ],

    'suitable_usage' => [
        'admin_name' => 'Suitable Usage',
        'translations' => [
            'ar' => 'الاستخدام المناسب',
            'en' => 'Suitable Usage',
        ],
        'type' => 'text',
        'group' => 'Product Details',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'suitable_usage', 'ar' => 'suitable_usage_ar'],
    ],

    'shape' => [
        'admin_name' => 'Shape',
        'translations' => [
            'ar' => 'الشكل',
            'en' => 'Shape',
        ],
        'type' => 'textarea',
        'group' => 'Construction',
        'required' => false,
        'filterable' => false,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'shape', 'ar' => 'shape_ar'],
    ],

    'compartments' => [
        'admin_name' => 'Compartments',
        'translations' => [
            'ar' => 'الأقسام الداخلية',
            'en' => 'Compartments',
        ],
        'type' => 'textarea',
        'group' => 'Construction',
        'required' => false,
        'filterable' => false,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'compartments', 'ar' => 'compartments_ar'],
    ],

    'pockets' => [
        'admin_name' => 'Pockets',
        'translations' => [
            'ar' => 'الجيوب',
            'en' => 'Pockets',
        ],
        'type' => 'textarea',
        'group' => 'Construction',
        'required' => false,
        'filterable' => false,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'pockets', 'ar' => 'pockets_ar'],
    ],

    'handles' => [
        'admin_name' => 'Handles',
        'translations' => [
            'ar' => 'المقابض',
            'en' => 'Handles',
        ],
        'type' => 'textarea',
        'group' => 'Construction',
        'required' => false,
        'filterable' => false,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'handles', 'ar' => 'handles_ar'],
    ],

    'shoulder_straps' => [
        'admin_name' => 'Shoulder Straps',
        'translations' => [
            'ar' => 'أحزمة الكتف',
            'en' => 'Shoulder Straps',
        ],
        'type' => 'textarea',
        'group' => 'Construction',
        'required' => false,
        'filterable' => false,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'shoulder_straps', 'ar' => 'shoulder_straps_ar'],
    ],

    'closure_type' => [
        'admin_name' => 'Closure Type',
        'translations' => [
            'ar' => 'نوع الغلق',
            'en' => 'Closure Type',
        ],
        'type' => 'select',
        'group' => 'Construction',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'pattern' => [
        'admin_name' => 'Pattern',
        'translations' => [
            'ar' => 'النقشة أو الرسومات',
            'en' => 'Pattern',
        ],
        'type' => 'textarea',
        'group' => 'Design',
        'required' => false,
        'filterable' => false,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'pattern', 'ar' => 'pattern_ar'],
    ],

    'printed_characters' => [
        'admin_name' => 'Printed Characters',
        'translations' => [
            'ar' => 'الشخصيات المطبوعة',
            'en' => 'Printed Characters',
        ],
        'type' => 'textarea',
        'group' => 'Design',
        'required' => false,
        'filterable' => false,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'printed_characters', 'ar' => 'printed_characters_ar'],
    ],

    'unique_characteristics' => [
        'admin_name' => 'Unique Characteristics',
        'translations' => [
            'ar' => 'الخصائص المميزة',
            'en' => 'Unique Characteristics',
        ],
        'type' => 'textarea',
        'group' => 'Design',
        'required' => false,
        'filterable' => false,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'unique_characteristics', 'ar' => 'unique_characteristics_ar'],
    ],

    'selling_points' => [
        'admin_name' => 'Selling Points',
        'translations' => [
            'ar' => 'نقاط البيع',
            'en' => 'Selling Points',
        ],
        'type' => 'textarea',
        'group' => 'Design',
        'required' => false,
        'filterable' => false,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'selling_points', 'ar' => 'selling_points_ar'],
    ],

    'size' => [
        'admin_name' => 'Size',
        'translations' => [
            'ar' => 'المقاس',
            'en' => 'Size',
        ],
        'type' => 'select',
        'group' => 'Specifications',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
        'options' => [
            '10 inch',
            '11 inch',
            '12 inch',
            '13 inch',
            '14 inch',
            '15 inch',
            '15.6 inch',
            '16 inch',
            '17 inch',
            '18 inch',
            '20 inch',
            '24 inch',
        ],
    ],

    'dimensions' => [
        'admin_name' => 'Dimensions',
        'translations' => [
            'ar' => 'الأبعاد',
            'en' => 'Dimensions',
        ],
        'type' => 'text',
        'group' => 'Specifications',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'dimensions', 'ar' => 'dimensions_ar'],
    ],

    'capacity' => [
        'admin_name' => 'Capacity',
        'translations' => [
            'ar' => 'السعة',
            'en' => 'Capacity',
        ],
        'type' => 'text',
        'group' => 'Specifications',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'capacity', 'ar' => 'capacity_ar'],
    ],

    'school_stage' => [
        'admin_name' => 'School Stage',
        'translations' => [
            'ar' => 'المرحلة الدراسية',
            'en' => 'School Stage',
        ],
        'type' => 'select',
        'group' => 'Meta Information',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
    ],

    'usage' => [
        'admin_name' => 'Usage',
        'translations' => [
            'ar' => 'الاستخدام',
            'en' => 'Usage',
        ],
        'type' => 'text',
        'group' => 'Meta Information',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'usage', 'ar' => 'usage_ar'],
    ],

    'occasion' => [
        'admin_name' => 'Occasion',
        'translations' => [
            'ar' => 'المناسبة',
            'en' => 'Occasion',
        ],
        'type' => 'text',
        'group' => 'Meta Information',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'occasion', 'ar' => 'occasion_ar'],
    ],

    'season' => [
        'admin_name' => 'Season',
        'translations' => [
            'ar' => 'الموسم',
            'en' => 'Season',
        ],
        'type' => 'text',
        'group' => 'Meta Information',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'season', 'ar' => 'season_ar'],
    ],

    'audience' => [
        'admin_name' => 'Audience',
        'translations' => [
            'ar' => 'الجمهور المستهدف',
            'en' => 'Audience',
        ],
        'type' => 'text',
        'group' => 'Meta Information',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => true,
        'value_per_channel' => false,
        'configurable' => false,
        'csv_columns' => ['en' => 'audience', 'ar' => 'audience_ar'],
    ],

    'available_colors' => [
        'admin_name' => 'Available Colors',
        'translations' => [
            'ar' => 'الألوان المتاحة',
            'en' => 'Available Colors',
        ],
        'type' => 'multiselect',
        'group' => 'Catalog',
        'required' => false,
        'filterable' => true,
        'searchable' => true,
        'comparable' => true,
        'visible_on_front' => true,
        'value_per_locale' => false,
        'value_per_channel' => false,
        'configurable' => false,
        'applies_to' => 'parent',
        'options' => [
            'Red',
            'Green',
            'Yellow',
            'Black',
            'White',
            'Mint Green',
            'Navy',
            'Pink',
            'Turquoise',
            'Purple',
            'Blue',
            'Ice Blue',
            'Lavender',
            'Pink Mint',
            'Mint',
            'Sky Blue',
            'Black Grey',
            'Navy Grey',
            'Black Brown',
            'Navy Green',
            'Navy Pink',
            'Dark Green',
            'Beige Yellow',
            'Pink Yellow',
            'Mauve',
            'Navy Tan',
            'Royal Blue',
            'Navy Red',
            'Grey Black',
            'Olive Green',
            'Grey',
            'Beige',
            'Grey Brown',
        ],
    ],

];
