name: Deploy Dragoon Production

on:
  push:
    branches:
      - main

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -i ~/.ssh/id_ed25519 \
          ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'

          set -e

          echo "===== Updating Source ====="

          cd /opt/apps/bagisto/source

          echo "===== Updating Source ====="
          git fetch origin
          git reset --hard origin/main

          # Remove only untracked files, but preserve storage
          git clean -fd -e storage

          echo "===== Fix Ownership ====="
          sudo chown -R deploy:deploy /opt/apps/bagisto/source

          echo "===== Docker ====="
          cd /opt/apps/bagisto/docker
          docker compose up -d --build

          echo "===== Laravel ====="
          docker exec bagisto-app composer install \
              --no-dev \
              --prefer-dist \
              --no-interaction \
              --optimize-autoloader

          docker exec bagisto-app php artisan optimize:clear

          docker exec bagisto-app php artisan migrate --force

          docker exec bagisto-app php artisan config:cache
          docker exec bagisto-app php artisan route:cache
          docker exec bagisto-app php artisan view:cache

          echo "===== Permissions ====="
          docker exec bagisto-app chown -R www-data:www-data storage bootstrap/cache
          docker exec bagisto-app chmod -R ug+rw storage bootstrap/cache

          echo "===== Health Check ====="
          curl -f https://dragoon-bag.com/up
